title:            The Book of Thoth
description:      "Speak magic. Unleash the power of language!"
logo:             logo.png
disqus_shortname: snorridev.github.io/thoth
share:            true
dropcap:	   true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same 
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	 http://snorridev.github.io/thoth/

# Owner/author information
owner:
  name:           SnorriDev
  avatar:         logo.png
  email:          snorri.devteam@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Speak magic. Unleash the power of language!
  # Social networking links used in footer. Update and remove as you like.
  twitter:        SnorriDev
  facebook:       SnorriDev
  github:         viking-sudo-rm 
  instagram:      lambdaviking
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/u/0/+AmeyJadiye

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-104939157-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: About
    url: /thoth/2017/08/13/What-is-The-Book-of-Thoth/
  - title: Categories
    url: /categories
  - title: Discord
    url: https://discord.gg/UzyUqQM

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
rouge: pygments
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   pretty

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

gems:
- jemoji
- jekyll-paginate
